//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoEditor.Presentation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float LastVolume {
            get {
                return ((float)(this["LastVolume"]));
            }
            set {
                this["LastVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastMuted {
            get {
                return ((bool)(this["LastMuted"]));
            }
            set {
                this["LastMuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentProjects {
            get {
                return ((string)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentFolders {
            get {
                return ((string)(this["RecentFolders"]));
            }
            set {
                this["RecentFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeepSeekApiKey {
            get {
                return ((string)(this["DeepSeekApiKey"]));
            }
            set {
                this["DeepSeekApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.deepseek.com")]
        public string DeepSeekBaseUrl {
            get {
                return ((string)(this["DeepSeekBaseUrl"]));
            }
            set {
                this["DeepSeekBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("whisper-1")]
        public string DeepSeekModel {
            get {
                return ((string)(this["DeepSeekModel"]));
            }
            set {
                this["DeepSeekModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("srt")]
        public string DeepSeekResponseFormat {
            get {
                return ((string)(this["DeepSeekResponseFormat"]));
            }
            set {
                this["DeepSeekResponseFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScreenRecorderSystemAudioDevice {
            get {
                return ((string)(this["ScreenRecorderSystemAudioDevice"]));
            }
            set {
                this["ScreenRecorderSystemAudioDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScreenRecorderMicrophoneDevice {
            get {
                return ((string)(this["ScreenRecorderMicrophoneDevice"]));
            }
            set {
                this["ScreenRecorderMicrophoneDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AiSubtitleProvidersJson {
            get {
                return ((string)(this["AiSubtitleProvidersJson"]));
            }
            set {
                this["AiSubtitleProvidersJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAiSubtitleProviderId {
            get {
                return ((string)(this["LastAiSubtitleProviderId"]));
            }
            set {
                this["LastAiSubtitleProviderId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AiSubtitleEnableOptimization {
            get {
                return ((bool)(this["AiSubtitleEnableOptimization"]));
            }
            set {
                this["AiSubtitleEnableOptimization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AiSubtitleOptimizationPrompt {
            get {
                return ((string)(this["AiSubtitleOptimizationPrompt"]));
            }
            set {
                this["AiSubtitleOptimizationPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FasterWhisperProgramPath {
            get {
                return ((string)(this["FasterWhisperProgramPath"]));
            }
            set {
                this["FasterWhisperProgramPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FasterWhisperModelDir {
            get {
                return ((string)(this["FasterWhisperModelDir"]));
            }
            set {
                this["FasterWhisperModelDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FasterWhisperModelsRootDir {
            get {
                return ((string)(this["FasterWhisperModelsRootDir"]));
            }
            set {
                this["FasterWhisperModelsRootDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FasterWhisperSelectedModel {
            get {
                return ((string)(this["FasterWhisperSelectedModel"]));
            }
            set {
                this["FasterWhisperSelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cpu")]
        public string FasterWhisperDevice {
            get {
                return ((string)(this["FasterWhisperDevice"]));
            }
            set {
                this["FasterWhisperDevice"] = value;
            }
        }
    }
}





